apps:
  bostonmusic:
    app_id: 20
    page:
      title: Boston Music Hub
    org: 
      name: exploitboston.com
      href: http://exploitboston.com
    poll_interval: 10
services:
  twitter: http://localhost:9494
  feeds: http://localhost:9393
